In [2]:
# Inicie importando as bibliotecas necess√°rias
import numpy as np
import pandas as pd
from numpy.linalg import norm
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
A = np.array([[1,0,1],[0,1,0],[1,1,1]])
b = np.array([1,2,3])
print(A*b)

[[1 0 3]
 [0 2 0]
 [1 2 3]]

In [4]:
data = pd.read_csv('data/bitcoin_price.csv')
data

,Date,Open,High,Low,Close,Volume,Market Cap
0,"Feb 20, 2018",11231.80,11958.50,11231.80,11403.70,"9,926,540,000","189,536,000,000"
1,"Feb 19, 2018",10552.60,11273.80,10513.20,11225.30,"7,652,090,000","178,055,000,000"
2,"Feb 18, 2018",11123.40,11349.80,10326.00,10551.80,"8,744,010,000","187,663,000,000"
3,"Feb 17, 2018",10207.50,11139.50,10149.40,11112.70,"8,660,880,000","172,191,000,000"
4,"Feb 16, 2018",10135.70,10324.10,9824.82,10233.90,"7,296,160,000","170,960,000,000"
5,"Feb 15, 2018",9488.32,10234.80,9395.58,10166.40,"9,062,540,000","160,025,000,000"
6,"Feb 14, 2018",8599.92,9518.54,8599.92,9494.63,"7,909,820,000","145,023,000,000"
7,"Feb 13, 2018",8926.72,8958.47,8455.41,8598.31,"5,696,720,000","150,516,000,000"
8,"Feb 12, 2018",8141.43,8985.92,8141.43,8926.57,"6,256,440,000","137,258,000,000"
9,"Feb 11, 2018",8616.13,8616.13,7931.10,8129.97,"6,122,190,000","145,245,000,000"
10,"Feb 10, 2018",8720.08,9122.55,8295.47,8621.90,"7,780,960,000","146,981,000,000"
11,"Feb 09, 2018",8271.84,8736.98,7884.71,8736.98,"6,784,820,000","139,412,000,000"
12,"Feb 08, 2018",7637.86,8558.77,7637.86,8265.59,"9,346,750,000","128,714,000,000"
13,"Feb 07, 2018",7755.49,8509.11,7236.79,7621.30,"9,169,280,000","130,683,000,000"
14,"Feb 06, 2018",7051.75,7850.70,6048.26,7754.00,"13,999,800,000","118,810,000,000"
15,"Feb 05, 2018",8270.54,8364.84,6756.68,6955.27,"9,285,290,000","139,325,000,000"
16,"Feb 04, 2018",9175.70,9334.87,8031.22,8277.01,"7,073,550,000","154,553,000,000"
17,"Feb 03, 2018",8852.12,9430.75,8251.63,9174.91,"7,263,790,000","149,085,000,000"
18,"Feb 02, 2018",9142.28,9142.28,7796.49,8830.75,"12,726,900,000","153,953,000,000"
19,"Feb 01, 2018",10237.30,10288.80,8812.28,9170.54,"9,959,400,000","172,372,000,000"
20,"Jan 31, 2018",10108.20,10381.60,9777.42,10221.10,"8,041,160,000","170,183,000,000"
21,"Jan 30, 2018",11306.80,11307.20,10036.20,10106.30,"8,637,860,000","190,339,000,000"
22,"Jan 29, 2018",11755.50,11875.60,11179.20,11296.40,"7,107,360,000","197,871,000,000"
23,"Jan 28, 2018",11475.30,12040.30,11475.30,11786.30,"8,350,360,000","193,133,000,000"
24,"Jan 27, 2018",11174.90,11614.90,10989.20,11440.70,"7,583,270,000","188,054,000,000"
25,"Jan 26, 2018",11256.00,11656.70,10470.30,11171.40,"9,746,200,000","189,398,000,000"
26,"Jan 25, 2018",11421.70,11785.70,11057.40,11259.40,"8,873,170,000","192,163,000,000"
27,"Jan 24, 2018",10903.40,11501.40,10639.80,11359.40,"9,940,990,000","183,419,000,000"
28,"Jan 23, 2018",10944.50,11377.60,10129.70,10868.40,"9,660,610,000","184,087,000,000"
29,"Jan 22, 2018",11633.10,11966.40,10240.20,10931.40,"10,537,400,000","195,645,000,000"
...,...,...,...,...,...,...,...
1730,"May 27, 2013",133.50,135.47,124.70,129.75,-,"1,495,520,000"
1731,"May 26, 2013",131.99,136.00,130.62,133.48,-,"1,478,030,000"
1732,"May 25, 2013",133.10,133.22,128.90,131.98,-,"1,489,950,000"
1733,"May 24, 2013",126.30,133.85,125.72,133.20,-,"1,413,300,000"
1734,"May 23, 2013",123.80,126.93,123.10,126.70,-,"1,384,780,000"
1735,"May 22, 2013",122.89,124.00,122.00,123.89,-,"1,374,130,000"
1736,"May 21, 2013",122.02,123.00,121.21,122.88,-,"1,363,940,000"
1737,"May 20, 2013",122.50,123.62,120.12,122.00,-,"1,368,910,000"
1738,"May 19, 2013",123.21,124.50,119.57,121.99,-,"1,376,370,000"
1739,"May 18, 2013",123.50,125.25,122.30,123.50,-,"1,379,140,000"
1740,"May 17, 2013",118.21,125.30,116.57,123.02,-,"1,319,590,000"
1741,"May 16, 2013",114.22,118.76,112.20,118.76,-,"1,274,620,000"
1742,"May 15, 2013",111.40,115.81,103.50,114.22,-,"1,242,760,000"
1743,"May 14, 2013",117.98,119.80,110.25,111.50,-,"1,315,720,000"
1744,"May 13, 2013",114.82,118.70,114.50,117.98,-,"1,279,980,000"
1745,"May 12, 2013",115.64,117.45,113.44,115.00,-,"1,288,630,000"
1746,"May 11, 2013",117.70,118.68,113.01,115.24,-,"1,311,050,000"
1747,"May 10, 2013",112.80,122.00,111.55,117.20,-,"1,255,970,000"
1748,"May 09, 2013",113.20,113.46,109.26,112.67,-,"1,259,980,000"
1749,"May 08, 2013",109.60,115.78,109.60,113.57,-,"1,219,450,000"
1750,"May 07, 2013",112.25,113.44,97.70,111.50,-,"1,248,470,000"
1751,"May 06, 2013",115.98,124.66,106.64,112.30,-,"1,289,470,000"
1752,"May 05, 2013",112.90,118.80,107.14,115.91,-,"1,254,760,000"
1753,"May 04, 2013",98.10,115.00,92.50,112.50,-,"1,089,890,000"
1754,"May 03, 2013",106.25,108.13,79.10,97.75,-,"1,180,070,000"
1755,"May 02, 2013",116.38,125.60,92.28,105.21,-,"1,292,190,000"
1756,"May 01, 2013",139.00,139.89,107.72,116.99,-,"1,542,820,000"
1757,"Apr 30, 2013",144.00,146.93,134.05,139.00,-,"1,597,780,000"
1758,"Apr 29, 2013",134.44,147.49,134.00,144.54,-,"1,491,160,000"
1759,"Apr 28, 2013",135.30,135.98,132.10,134.21,-,"1,500,520,000"